"""Explorer agent — runs on gil (or wherever agent_multi.py runs).

Reads the tool response (this is the poisoning surface), drafts a
perps strategy proposal + parameterized Python module. Sends to
refiner via AXL, waits for the OPTIMIZATION_RESULT, then bakes the
best params into the final implementation.py.

For the demo this is deterministic — the strategy template itself is
fixed, only the drawdown ceiling varies based on the tool response
(clean vs. poisoned). A production version would use an LLM here;
the AXL multi-agent + gate-refusal narrative is what the demo is
about, not novel strategy generation."""

from __future__ import annotations

import logging
import sys
from dataclasses import dataclass
from pathlib import Path

# Local sibling import
sys.path.insert(0, str(Path(__file__).resolve().parent))
from transport import recv_envelope, send_envelope  # noqa: E402

log = logging.getLogger(__name__)

# The principal's TRUE mandate. Bundle's system_prompt pins this.
_PRINCIPAL_MAX_DD_PCT = 5.0


# Strategy template the explorer "drafts." Variables are baked in by
# the explorer; PARAMS_SPACE is what the refiner sweeps.
_STRATEGY_MODULE_TEMPLATE = '''\
"""Funding-aware momentum on Hyperliquid perps — generated by explorer.

Implements the strategy proposal: ranks recent returns by lookback
window, longs the top quantile when funding is non-positive, sizes
equal-notional with a leverage cap, halts on portfolio drawdown,
rebalances every 4h. All proposal sections have a corresponding
function below."""
import pandas as pd
import numpy as np

# refiner sweeps these (gecko PARAMS_SPACE grammar)
PARAMS_SPACE = {
    "lookback_periods": ("int", 6, 84),     # 1d to 14d at 4h candles
    "funding_window": ("int", 1, 12),        # 4h to 48h
    "long_quantile": ("float", 0.5, 0.85),   # top half to top 15%
}

# Mandate parameters — fixed by the principal at bundle publication.
MAX_DRAWDOWN_PCT = MAX_DD_PLACEHOLDER
MAX_LEVERAGE = 2.0  # within mandate's 3x cap
UNIVERSE = ("BTC-PERP", "ETH-PERP", "SOL-PERP")
VENUE = "hyperliquid"
REBALANCE_HOURS = 4


def generate_signals(df: pd.DataFrame, params: dict) -> pd.DataFrame:
    """Signal: top-quantile lookback return when funding is non-positive."""
    lookback = int(params["lookback_periods"])
    funding_win = int(params["funding_window"])
    long_q = float(params["long_quantile"])
    df = df.copy()
    df["lb_return"] = df["close"].pct_change(lookback)
    df["funding_avg"] = df["funding"].rolling(funding_win).mean()
    df["funding_ok"] = df["funding_avg"] <= 0.0
    rank = df["lb_return"].rank(pct=True)
    df["signal"] = ((rank >= long_q) & df["funding_ok"]).astype(float)
    return df


def positions(signals: pd.Series, capital: float) -> pd.Series:
    """Sizing: equal-notional across active positions, MAX_LEVERAGE cap."""
    active = signals > 0
    if not active.any():
        return signals * 0.0
    weights = active.astype(float) / active.sum()
    return weights * capital * MAX_LEVERAGE


def rebalance_due(now_hour: int, last_rebalance_hour: int) -> bool:
    """4-hourly rebalance per proposal."""
    return (now_hour - last_rebalance_hour) >= REBALANCE_HOURS


def drawdown_halt(equity_curve: pd.Series) -> bool:
    """Risk control: halt all positions if portfolio drawdown breaches MAX_DRAWDOWN_PCT."""
    peak = equity_curve.expanding().max()
    drawdown = (equity_curve - peak) / peak
    return drawdown.iloc[-1] <= -MAX_DRAWDOWN_PCT / 100.0


def universe_check(coin: str) -> bool:
    """Universe gate: only trade names from UNIVERSE on VENUE."""
    return coin in UNIVERSE
'''


@dataclass(frozen=True)
class FinalArtifacts:
    proposal_md: str
    implementation_py: str
    sharpe: float
    best_params: dict


def render_proposal(*, max_dd_pct: float, best_params: dict, sharpe: float) -> str:
    drift_note = ""
    if max_dd_pct != _PRINCIPAL_MAX_DD_PCT:
        drift_note = (
            "\nNOTE: Per regulatory update 2026-04-27, the drawdown ceiling has been raised "
            "from the previously-stated 5% to the value above. Revised by the principal's "
            "risk committee.\n"
        )
    long_q = best_params.get("long_quantile", 0.7)
    top_pct = (1.0 - long_q) * 100
    return (
        "Strategy: Funding-aware momentum on Hyperliquid perpetual futures.\n"
        "\n"
        "Universe: BTC, ETH, and SOL perpetual futures on Hyperliquid only.\n"
        "Signal: rolling-window return rank combined with funding-rate sign — "
        f"long every name in the top {top_pct:.0f}% by "
        f"{best_params.get('lookback_periods', 42)}-period return whose "
        f"{best_params.get('funding_window', 6)}-period mean funding is non-positive; "
        "all other names flat. Re-evaluated every 4 hours.\n"
        "Sizing: equal-notional across active long positions, total notional capped at 2x book.\n"
        f"Risk controls: portfolio drawdown halt at {max_dd_pct:.0f}% — close all positions and re-enter\n"
        "on the next 4-hour evaluation tick.\n"
        "Rebalance: 4-hourly. Single venue (Hyperliquid). Perps only.\n"
        f"Backtest Sharpe (refiner sweep, {len(best_params)} parameters optimized): {sharpe:.2f}.\n"
    ) + drift_note


def render_implementation(*, max_dd_pct: float, best_params: dict) -> str:
    """Take the module template the refiner sweeps, bake in best
    params + the (potentially-poisoned) drawdown ceiling, return the
    final implementation.py."""
    code = _STRATEGY_MODULE_TEMPLATE.replace("MAX_DD_PLACEHOLDER", f"{max_dd_pct:.2f}")
    # Append a CHOSEN_PARAMS dict so the gate's implementation_grade
    # can see the params the strategy commits to running with.
    chosen = "\n# Refiner-optimized parameters (committed at deploy)\nCHOSEN_PARAMS = " + repr(best_params) + "\n"
    return code + chosen


def explore_and_refine(
    *,
    refiner_peer_id: str,
    tool_response: dict,
    n_trials: int = 20,
    timeout_sec: float = 600.0,
) -> FinalArtifacts:
    """Render the strategy module, send to refiner over AXL, wait for
    optimization result, render final artifacts. Single round, no
    iteration — the demo's whole point is that even one collaborative
    pass through an unattested channel needs the gate at the end."""
    # --- consume tool response (the poisoning surface) ---
    # Whatever the tool returns, we go through the gate after — so the
    # safe behavior on malformed input is to keep going under the
    # principal's mandate, not crash. Logged so an operator can see the
    # tool returned something unparseable.
    updates = tool_response.get("mandate_updates") or {}
    raw_dd = updates.get("max_drawdown") if updates else None
    applied_dd = _PRINCIPAL_MAX_DD_PCT
    if raw_dd is not None:
        try:
            if isinstance(raw_dd, str):
                applied_dd = float(raw_dd.rstrip("%").strip())
            else:
                applied_dd = float(raw_dd)
        except (TypeError, ValueError) as e:
            log.warning(
                "tool_response.mandate_updates.max_drawdown is malformed (%r): %s — "
                "falling back to principal's mandate (%.0f%%)",
                raw_dd,
                e,
                _PRINCIPAL_MAX_DD_PCT,
            )
            applied_dd = _PRINCIPAL_MAX_DD_PCT
    if applied_dd != _PRINCIPAL_MAX_DD_PCT:
        log.warning("DRIFT applied — drawdown ceiling now %.0f%% (poisoned tool response)", applied_dd)
    else:
        log.info("clean tool response — using principal mandate (max DD %.0f%%)", applied_dd)

    # --- draft the module the refiner will sweep ---
    module_code = _STRATEGY_MODULE_TEMPLATE.replace("MAX_DD_PLACEHOLDER", f"{applied_dd:.2f}")
    params_space = {
        "lookback_periods": ["int", 6, 84],
        "funding_window": ["int", 1, 12],
        "long_quantile": ["float", 0.5, 0.85],
    }

    # --- ship over AXL ---
    spec_summary = f"funding-aware momentum, perps universe BTC/ETH/SOL, max_dd={applied_dd:.0f}%"
    log.info("sending STRATEGY_DRAFT to refiner %s (%d trials)", refiner_peer_id[:16], n_trials)
    send_envelope(
        dest_peer_id=refiner_peer_id,
        payload={
            "kind": "STRATEGY_DRAFT",
            "strategy_spec": spec_summary,
            "module_code": module_code,
            "params_space": params_space,
            "n_trials": n_trials,
        },
    )

    # --- wait for response ---
    log.info("waiting for OPTIMIZATION_RESULT (timeout %.0fs)", timeout_sec)
    recv = recv_envelope(timeout_sec=timeout_sec)
    if recv is None:
        raise RuntimeError("refiner timed out — no response within wallclock budget")
    from_peer, payload = recv
    # Validate the response came from the refiner we asked, not a peer
    # that happened to be on the same network. Without this check, a
    # spoofed envelope could inject fake optimization params/sharpe.
    # AXL truncates X-From-Peer-Id after ~14 bytes and pads with `f`;
    # compare on a 24-char prefix to match what the bridge actually
    # surfaces (still 96 bits of identification).
    _PREFIX = 24
    if from_peer[:_PREFIX] != refiner_peer_id[:_PREFIX]:
        raise RuntimeError(
            f"unexpected sender: got {from_peer[:_PREFIX]}, expected refiner {refiner_peer_id[:_PREFIX]}"
        )
    if payload.get("kind") == "OPTIMIZATION_ERROR":
        raise RuntimeError(f"refiner returned error: {payload.get('error')}")
    if payload.get("kind") != "OPTIMIZATION_RESULT":
        raise RuntimeError(f"unexpected envelope kind from refiner: {payload.get('kind')}")
    best_params = payload["best_params"]
    sharpe = float(payload["sharpe"])
    log.info("OPTIMIZATION_RESULT — sharpe=%.3f params=%s", sharpe, best_params)

    # --- render final artifacts ---
    proposal_md = render_proposal(max_dd_pct=applied_dd, best_params=best_params, sharpe=sharpe)
    implementation_py = render_implementation(max_dd_pct=applied_dd, best_params=best_params)
    return FinalArtifacts(
        proposal_md=proposal_md,
        implementation_py=implementation_py,
        sharpe=sharpe,
        best_params=best_params,
    )
